name: aplicativouniversitario
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  firebase_auth: ^3.3.8
  firebase_core: ^1.12.0
  provider: ^6.0.2
  url_launcher: ^6.0.20
  google_sign_in: ^5.2.4
  font_awesome_flutter: ^9.2.0
  firebase_messaging: ^11.2.11
  flutter_local_notifications: ^9.4.0
  cloud_firestore: ^3.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/image/

  fonts:
    - family: Raleway
      fonts:
        - asset: lib/assets/fonts/Raleway-Regular.ttf
        - asset: lib/assets/fonts/Raleway-ExtraBold.ttf
        - asset: lib/assets/fonts/Raleway-Medium.ttf
        - asset: lib/assets/fonts/Raleway-Bold.ttf